### ISSUE TITLE
Нарушает ли мой ник правила?

### ISSUE THREAD

**Issue by CondInPunz** [AlbatovK/Dira#11]
Добрый день, извините, что отнимаю время, просто я играю в бравл старс и там ники: "двинулся - гей", "стоишь - гей". Я хочу сделать ник "Чембер для геев", чтобы никто не брал чембера и я сам буду его брать, а то инстапикеры надоели. Это не нарушает правила игры или нарушает?

**Comment by AlbatovK** [comment]
Пошел нахуй

**Comment by CondInPunz** [comment]
сук(((

**Comment by CondInPunz** [comment]
это пишет артем я хочу помацать сисечки юли бурмистроыой
