### ISSUE TITLE
Ускорение работы приложения

### ISSUE THREAD

**Issue by AkkaRin11** [AlbatovK/Dira#3]
Приложение слишком долго обрабатывает запросы даже при хорошем(относительно) интернете. Это затрудняет пользование.

**Comment by AlbatovK** [comment]
Здравствуйте, дорогой пользователь. Мы готовы пойти вам навстречу. Мы уже стоим на пороге открытия, позволяющего нам совершить прорыв в области скорости работы приложения.

**Comment by AlbatovK** [comment]
Я сделал метод, который обрабатывает список вместо отдельных заметок. Теперь скорость добавления сильно увеличена

**Comment by CondInPunz** [comment]
мнение подворного не учитывается
